name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.5
      uses: actions/setup-python@v3
      with:
        python-version: '3.13.5'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Install pytest
      run: |
        conda install pytest
    - name: Test A basics
      run: |
        pytest ./tests/test_a_basics.py
    - name: Test B collections I/O
      run: |
        pytest ./tests/test_b_collections_io.py
    - name: Test C module
      run: |
        pytest ./tests/test_c_module.py
