name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.13.5'
        auto-activate-base: true
        auto-update-conda: true

    - name: Install dependencies
      run: |
        # It's good practice to install pip within your conda env
        conda install pip --yes
        # Install testing dependencies
        conda install pytest --yes

    - name: Install project
      run: |
        # This is the crucial step that fixes the ModuleNotFoundError
        # The '-e' means "editable mode"
        pip install -e .

    - name: Run tests
      run: |
        pytest ./tests/