name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.13.5'
        auto-activate-base: true
        auto-update-conda: true

    - name: Install dependencies into base environment
      run: |
        conda install --file environment.yml

    - name: Run tests
      run: |
        pytest ./tests/